<h2 class="publicSubtitle">Solicitação de nova senha</h2>
<?php if (empty($this->formProcessed)): ?>
<div class="newPassword">
    <p>
        Para proteger a privacidade dos usuários, todas as senhas estão criptografadas.
        Se você esqueceu a sua, não podemos recuperá-la.
    </p>
    <p>
        Por favor, preencha o campo abaixo com seu e-mail registrado e o sistema
        enviará um link para que você efetue a alteração da senha:
    </p>
</div>
<?php if (!empty($this->formResponse)): ?>
<div id="passwordError">
    <strong><?= $this->formResponseTitle; ?></strong>
    <p><?= $this->formResponse; ?></p>
</div>
<?php endif; ?>
<?= $this->form; ?>
<?php else: ?>
<div id="passwordError">
    <strong><?= $this->formResponseTitle; ?></strong>
    <p><?= $this->formResponse; ?></p>
</div>
<?php endif; ?>
<p><a href="<?= $this->url(array('controller'=>'index', 'action'=>'index'), null); ?>">Voltar</a></p>