<?= $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="pt-br" lang="pt-br">

    <head>
        <?php
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/reset.css' , 'all');
        $this->headLink()->appendStylesheet($this->baseUrl() . '/css/public.css' , 'all');

        $this->headScript()->appendFile($this->baseUrl().'/js/jquery.js');
        $this->headScript()->appendFile($this->baseUrl().'/js/public.js');
        $this->headScript()->appendFile($this->baseUrl().'/js/numera.form.js');

        ?>

        <?= $this->HeadMeta(); ?>
        <?= $this->headTitle(); ?>
        <?= $this->headLink(); ?>

        <!--[if IE 6]>
            <link rel="stylesheet" href="./css/iefix.default.css" type="text/css"/>
            <![endif]-->

        <!--[if IE 7]>
            <link rel="stylesheet" href="./css/iefix.default.css" type="text/css"/>
            <![endif]-->

    </head>

    <body onLoad="var z=document.getElementById('email'); if(z){z.focus()}">
        <div id="verticalOuter">
            <div id="verticalInner">
                <h1 id="top"></h1>
                <div id="content">
                    <h1><?= $this->siteTitle ?></h1>
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="bottom"></div>
            </div>
        </div>
    </body>

</html>