<form id="programmingForm" class="structured" enctype="application/x-www-form-urlencoded" accept-charset="UTF-8" action="<?= $this->actionUrl ?>" method="post">
    <fieldset id="fieldset-descriptions" class="programmingGroup">
        <legend>Descrições</legend>
        <div class="formRow">
            <label for="description" class="formLabel required">Descrição:*</label>
            <div class="formElement">
                <textarea name="description" id="description" class="formElementTextareaLimited" rows="24" cols="80"></textarea>
                <div class="hint">Descrição da programação</div>
            </div>
        </div>
        <div class="formRow">
            <label for="dt_start" class="formLabel required">Início:*</label>
            <div class="formElement">
                <input type="text" name="dt_start" id="dt_start" value="" class="formElementDate" />
                <div class="hint">Coloque a data no formato dd/mm/aaaa (dia/mês/ano).</div>
            </div>
        </div>
        <div class="formRow">
            <label for="dt_end" class="formLabel optional">Término:</label>
            <div class="formElement">
                <input type="text" name="dt_end" id="dt_end" value="" class="formElementDate" />
                <div class="hint">Coloque a data no formato dd/mm/aaaa (dia/mês/ano).</div>
            </div>
        </div>
        <div class="formRow">
            <label for="time" class="formLabel required">Horários:*</label>
            <div class="formElement">
                <input type="text" name="time" id="time" value="" class="formElementMultiValues formElementTime" />
                <div class="hint">Horário que a conta irá receber a programação</div>
            </div>
        </div>
        <?php if($this->sendOption == 1){ ?>
        <div class="formRow">
            <div class="formElement">
                <input type="hidden" name="reminder" id="reminder" value="" class="formElementInteger" />
                <div class="hint">Periodicidade dos lembretes (em minutos)</div>
            </div>
        </div>
<!--        <div class="formRow">
            <label for="reminder" class="formLabel optional">Lembretes a cada:</label>
            <div class="formElement">
                <input type="text" name="reminder" id="reminder" value="" class="formElementInteger" />
                <div class="hint">Periodicidade dos lembretes (em minutos)</div>
            </div>
        </div>-->
        <?php } else { ?>
        <div class="formRow">
            <div class="formElement">
                <input type="hidden" name="reminder" id="reminder" value="" class="formElementInteger" />
                <div class="hint">Periodicidade dos lembretes (em minutos)</div>
            </div>
        </div>
        <?php } ?>
        <div class="formRow">
            <label for="in_repetition" class="formLabel required">Tipo de Repetição:*</label>
            <div class="formElement">
                <label for="in_repetition-0" style="display:none"><input type="radio" name="in_repetition" id="in_repetition-0" value="0" class="formElementRadio formElementInteract"  />Nenhuma</label><br />
                <label for="in_repetition-1"><input type="radio" name="in_repetition" id="in_repetition-1" value="1" class="formElementRadio formElementInteract" checked="checked" />Com freqüencia</label><br />
                <label for="in_repetition-2" style="display:none"><input type="radio" name="in_repetition" id="in_repetition-2" value="2" class="formElementRadio formElementInteract" />Com interrupção</label>
            </div>
        </div>

        <fieldset id="interact-in_repetition-1" class="interactElement interactElement-in_repetition">
            <div class="formRow">
                <label for="frequency" class="formLabel optional">Freqüencia:</label>
                <div class="formElement">
                    <select name="frequency" id="frequency" class="formElementSelect formElementInteract">
                        <option value="1" label="Diária">Diária</option>
                        <option value="2" label="Semanal">Semanal</option>
                        <option value="3" label="Mensal">Mensal</option>
                        <option value="4" label="Anual">Anual</option>
                    </select>
                </div>
            </div>

            <fieldset id="frequency-2" class="interactElement interactElement-frequency">
                <div class="formRow">
                    <label for="week_frequency" class="formLabel optional">Selecione o(s) dia(s):</label>
                    <div class="formElement">
                        <label for="week_frequency-1"><input type="checkbox" name="week_frequency[]" id="week_frequency-1" value="1" class="formElementMultiCheckbox" />Segunda</label><br />
                        <label for="week_frequency-2"><input type="checkbox" name="week_frequency[]" id="week_frequency-2" value="2" class="formElementMultiCheckbox" />Terça</label><br />
                        <label for="week_frequency-3"><input type="checkbox" name="week_frequency[]" id="week_frequency-3" value="3" class="formElementMultiCheckbox" />Quarta</label><br />
                        <label for="week_frequency-4"><input type="checkbox" name="week_frequency[]" id="week_frequency-4" value="4" class="formElementMultiCheckbox" />Quinta</label><br />
                        <label for="week_frequency-5"><input type="checkbox" name="week_frequency[]" id="week_frequency-5" value="5" class="formElementMultiCheckbox" />Sexta</label><br />
                        <label for="week_frequency-6"><input type="checkbox" name="week_frequency[]" id="week_frequency-6" value="6" class="formElementMultiCheckbox" />Sábado</label><br />
                        <label for="week_frequency-7"><input type="checkbox" name="week_frequency[]" id="week_frequency-7" value="7" class="formElementMultiCheckbox" />Domingo</label>
                    </div>
                </div>
            </fieldset>

            <fieldset id="frequency-3" class="interactElement interactElement-frequency">
                <div class="formRow">
                    <label for="mouth_frequency" class="formLabel optional">Selecione o dia do mês:</label>
                    <div class="formElement">
                        <select name="mouth_frequency" id="mouth_frequency" class="formElementSelect formElementMultiValues">
                            <option value="1" label="1">1</option>
                            <option value="2" label="2">2</option>
                            <option value="3" label="3">3</option>
                            <option value="4" label="4">4</option>
                            <option value="5" label="5">5</option>
                            <option value="6" label="6">6</option>
                            <option value="7" label="7">7</option>
                            <option value="8" label="8">8</option>
                            <option value="9" label="9">9</option>
                            <option value="10" label="10">10</option>
                            <option value="11" label="11">11</option>
                            <option value="12" label="12">12</option>
                            <option value="13" label="13">13</option>
                            <option value="14" label="14">14</option>
                            <option value="15" label="15">15</option>
                            <option value="16" label="16">16</option>
                            <option value="17" label="17">17</option>
                            <option value="18" label="18">18</option>
                            <option value="19" label="19">19</option>
                            <option value="20" label="20">20</option>
                            <option value="21" label="21">21</option>
                            <option value="22" label="22">22</option>
                            <option value="23" label="23">23</option>
                            <option value="24" label="24">24</option>
                            <option value="25" label="25">25</option>
                            <option value="26" label="26">26</option>
                            <option value="27" label="27">27</option>
                            <option value="28" label="28">28</option>
                            <option value="29" label="29">29</option>
                            <option value="30" label="30">30</option>
                            <option value="31" label="31">31</option>
                        </select>
                    </div>
                </div>
            </fieldset>

            <fieldset id="frequency-4" class="interactElement interactElement-frequency">
                <div class="formRow">
                    <label for="year_mouth_frequency" class="formLabel required">Selecione o dia do mês:</label>
                    <div class="formElement">
                        <select name="year_day_frequency" id="year_day_frequency" class="inline">
                            <option value="1" label="1">1</option>
                            <option value="2" label="2">2</option>
                            <option value="3" label="3">3</option>
                            <option value="4" label="4">4</option>
                            <option value="5" label="5">5</option>
                            <option value="6" label="6">6</option>
                            <option value="7" label="7">7</option>
                            <option value="8" label="8">8</option>
                            <option value="9" label="9">9</option>
                            <option value="10" label="10">10</option>
                            <option value="11" label="11">11</option>
                            <option value="12" label="12">12</option>
                            <option value="13" label="13">13</option>
                            <option value="14" label="14">14</option>
                            <option value="15" label="15">15</option>
                            <option value="16" label="16">16</option>
                            <option value="17" label="17">17</option>
                            <option value="18" label="18">18</option>
                            <option value="19" label="19">19</option>
                            <option value="20" label="20">20</option>
                            <option value="21" label="21">21</option>
                            <option value="22" label="22">22</option>
                            <option value="23" label="23">23</option>
                            <option value="24" label="24">24</option>
                            <option value="25" label="25">25</option>
                            <option value="26" label="26">26</option>
                            <option value="27" label="27">27</option>
                            <option value="28" label="28">28</option>
                            <option value="29" label="29">29</option>
                            <option value="30" label="30">30</option>
                            <option value="31" label="31">31</option>
                        </select>
                    </div>
                </div>
                <div class="formRow">
                    <div class="formElement">
                        <select name="year_mouth_frequency" id="year_mouth_frequency" class="inline">
                            <option value="1" label="Janeiro">Janeiro</option>
                            <option value="2" label="Fevereiro">Fevereiro</option>
                            <option value="3" label="Março">Março</option>
                            <option value="4" label="Abril">Abril</option>
                            <option value="5" label="Maio">Maio</option>
                            <option value="6" label="Junho">Junho</option>
                            <option value="7" label="Julho">Julho</option>
                            <option value="8" label="Agosto">Agosto</option>
                            <option value="9" label="Setembro">Setembro</option>
                            <option value="10" label="Outubro">Outubro</option>
                            <option value="11" label="Novembro">Novembro</option>
                            <option value="12" label="Dezembro">Dezembro</option>
                        </select>
                    </div>
                </div>
            </fieldset>
        </fieldset>

        <fieldset id="interact-in_repetition-2" class="interactElement interactElement-in_repetition">
            <div class="formRow">
                <div class="formElement">
                    <label for="interrupt-0"><input checked="" type="radio" class="formElementRadio" value="0" id="interrupt-0" name="interrupt" /></label>Envio durante <input type="text" style="width:30px" id="during_days" /> dias com a interrupção de <input type="text" style="width:30px" id="interrupt_days" /> dias.<br/>
                    <label for="interrupt-1"><input type="radio" class="formElementRadio" value="1" id="interrupt-1" name="interrupt" /></label>Envia a cada <input type="text" style="width:30px" id="interval_days" /> dias.
                </div>
            </div>
        </fieldset>

        <input type="hidden" id="descriptionsProgrammingValues" class="formElementHidden" value="" name="descriptionsProgrammingValues"/>
                <input type="hidden"  class="formElementHidden" value="0" name="checkform"/>
    </fieldset>

    <div class="formRow">
        <div class="formElement">
            <input type="submit" name="confirm" id="confirm" value="Confirmar" class="formElementSubmit" />
        </div>
    </div>
</form>
<style>
    
    #sidebar{
        display: none;
    }
    
    .help_with{
        display: none;
    }
</style>